### ISSUE TITLE
参考文献的格式还得修改

### ISSUE THREAD

**Issue by hkunzhe** [BlurryLight/CSU-Thesis-LaTeX-Template#2]
学校的模板要求参考文献：
+ 采用五号楷体GB2312，同正文1.5倍行间距。
+ 引用需要括号上标的形式

可以尝试使用https://github.com/hushidong/biblatex-gb7714-2015

**Comment by BlurryLight** [comment]
- 参考文献的问题我知道，不过因为我还在赶文章所以还没有空来改，欢迎pull request。
- 引用的问题master分支应该已经修复了。你可以使用\cite和\supercite命令，分别对应正常引用和上标引用。

**Comment by BlurryLight** [comment]
Fixed by https://github.com/BlurryLight/CSU-Thesis-LaTeX-Template/pull/3
