### ISSUE TITLE
同学你好，你的英文摘要的中文摘要和参考文献的行间距和中南大学论文格式要求不符合可以修改下嘛

### ISSUE THREAD

**Issue by qq2214227433** [BlurryLight/CSU-Thesis-LaTeX-Template#5]
同学你好，你的英文摘要的中文摘要和参考文献的行间距和中南大学论文格式要求不符合可以修改下嘛

**Comment by hkunzhe** [comment]
你好，中英文摘要以及参考文献均设置为1.5倍的行距，符合学校提供的模板的要求。

**Comment by BlurryLight** [comment]
你好，关于中文摘要和英文摘要的问题，如果你的摘要无法通过学院的格式审查，可以酌情修改以下两处，当前的行间距设置为1.5倍 ：https://github.com/BlurryLight/CSU-Thesis-LaTeX-Template/blob/f34b97db2f5c34f031ec37a2b5f28ad5771a93f7/CSUthesis.cls#L256
https://github.com/BlurryLight/CSU-Thesis-LaTeX-Template/blob/f34b97db2f5c34f031ec37a2b5f28ad5771a93f7/CSUthesis.cls#L279

参考文献遵循GB7714-2015的强制要求，如果学校提供的模版与GB7714-2015表现有差异，应该以国标为准。
